# Generated by Django 5.2 on 2025-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='DOB',
            new_name='dob',
        ),
    ]
